name: Deploy Streamlit App to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-space:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Clone Hugging Face Space repository
        env:
          TARGET_HF_SPACE_URL: https://user:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ github.repository_owner }}/${{ github.event.repository.name }}
        run: |
          sudo apt-get update && sudo apt-get install -y git-lfs
          git lfs install --system --skip-repo
          git clone "$TARGET_HF_SPACE_URL" hf_space
          cd hf_space
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Sync files to Space repository
        run: |
          cd hf_space
          find . -path ./.git -prune -o -exec rm -rf {} \; 2>/dev/null || true
          rsync -av --delete --exclude='.git/' --exclude='.github/' --exclude='hf_space/' $GITHUB_WORKSPACE/ ./
          if [ -f "$GITHUB_WORKSPACE/.gitattributes" ]; then
            cp "$GITHUB_WORKSPACE/.gitattributes" .
          fi

      - name: Commit and Push to Hugging Face Space
        run: |
          cd hf_space
          MODEL_EXTENSION="spam_classifier.pkl" # Model uzantınız farklıysa değiştirin
          git lfs track "*.${MODEL_EXTENSION}"
          git add .
          if [ -f ".gitattributes" ]; then
            git add .gitattributes --force
          fi
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update from GitHub Action ${{ github.sha }}"
            git push origin main
            echo "Push successful!"
          else
            echo "No changes detected in hf_space to commit."
          fi
